use oposiciones;
INSERT INTO ETIQUETA (etiquetaId, nombre) VALUES
(72, 'Administración General del Estado'),
(73, 'Ministerio del Interior'),
(74, 'Tribunal Constitucional'),
(75, 'Ministerio de Ciencia, Innovación y Universidades'),
(76, 'Diputación Provincial'),
(77, 'Ayuntamiento de Avilés'),
(78, 'Ayuntamiento de Gijón'),
(79, 'Ayuntamiento de Villanueva de la Cañada'),
(80, 'Ayuntamiento de Torrelodones'),
(81, 'Ayuntamiento de Palma de Mallorca'),
(82, 'Ayuntamiento de Villanueva de la Serena'),
(83, 'Ayuntamiento de Dos Hermanas'),
(84, 'Ayuntamiento de Almensilla'),
(85, 'Ayuntamiento de Sanlúcar la Mayor'),
(86, 'Ayuntamiento de Barcelona'),
(87, 'Ayuntamiento de Madrid'),
(88, 'Informática'),
(89, 'Medioambiente y Patrimonio'),
(90, 'Policía Local'),
(91, 'Trabajador Familiar'),
(92, 'Conserje'),
(93, 'Intendente'),
(94, 'Gestión de Personal'),
(95, 'Ordenanza'),
(96, 'Operario Lavandería Costura Limpieza'),
(97, 'Monitor Tiempo Libre'),
(98, 'Arquitecto'),
(99, 'Jardinero'),
(100, 'Electricista'),
(101, 'Educador'),
(102, 'Educador Infantil'),
(103, 'Auxiliar Administrativo'),
(104, 'Guardia Municipal'),
(105, 'Administrativo'),
(106, 'Cabo'),
(107, 'Agente Policía Local'),
(108, 'Técnico Administración General');
